<!-- Promise .then() and .catch() -->


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Promise .then() and .catch()</title>
</head>
<body>
    <h2>Promise .then() and .catch()</h2>
</body>

<script>

    let p1=new Promise((resolve,reject)=>{
        console.log('promise is pending')

        setTimeout(() => {
            console.log('so my promsese is rejected')
            resolve(console.log('THE PROMESE IS RESOLVED'))
        }, 5000);
        
    })

    // console.log(p1)

    // then()
   /* p1.then((value)=>{
        console.log(value)
    }) */

    // we can also catch the error here in then
    p1.then((value)=>{
        console.log(value)
    },(error)=>{
        console.log(error)
    })



    let p2=new Promise((resolve,reject)=>{
        console.log('promise is pending')

        setTimeout(() => {
            console.log('so my promsese is rejected')
            reject(new Error('showing error'))
        }, 5000);
        
    })

    // console.log(p2)
    
    // To catch the errors
    p2.catch((error)=>{
        console.log(error)
    })

  
</script>
</html>